spring:
  application:
    name: splitup-backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5430}/${POSTGRES_DB:splitup}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    show-sql: true

server:
  port: ${APP_PORT:8080}